# Generated by Django 4.1.5 on 2023-01-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='yearinventory_quantity',
            new_name='inventory_quantity',
        ),
    ]
